---
platform: linux

image_resource:
  type: docker-image
  source: {repository: golang, tag: "1"}

run:
  path: app-master/ci/scripts/build.sh

inputs:
  - name: app-master

outputs:
  - name: artifacts
  