---
platform: linux

image_resource:
  type: docker-image
  source: 
      repository: quay.io/hellofresh/api-gateway
      username: {{quay_username}}
      password: {{quay_password}}

run:
  path: sh
  args:
    - -exec
    - api-gateway/ci/tasks/deploy-staging.sh

inputs:
  - name: automation-release
  - name: api-gateway-rc
  - name: api-gateway
    