---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: quay.io/hellofresh/docker-php-ci

inputs:
  - name: source-code
  - name: release-candidate

outputs:
  - name: artifacts

run:
  path: source-code/ci/scripts/extract-release.sh
