---
platform: linux

image_resource:
  type: docker-image
  source: 
      repository: quay.io/hellofresh/api-gateway
      username: {{quay_username}}
      password: {{quay_password}}

run:
  path: api-gateway/ci/tasks/unit-tests.sh

inputs:
- name: prequest