version: '2'
services:

    janus:
      depends_on:
        - mongodb
        - redis
        - statsd
      image: quay.io/hellofresh/janus
      ports:
        - "8080:8080"
      environment:
      # required
        DATABASE_DSN: 'mongodb://mongodb:27017/janus'
        REDIS_DSN: 'redis:6379'
        SECRET: 'secret key'
      # not required
    #         PORT: '8080'
    #         DEBUG: 'false'
    #         LOG_LEVEL: 'debug'
    #         STATSD_DSN: 'statsd:8125'
    #         STATSD_PREFIX: 'janus-docker.'
    #         ADMIN_USERNAME: 'admin'
    #         ADMIN_PASSWORD: 'admin'
    #         GRACE_TIMEOUT: '10'
    #         MAX_IDLE_CONNS_PER_HOST: '200'
    #         INSECURE_SKIP_VERIFY: 'false'

    mongodb:
        image: mongo
        ports:
            - "27017:27017"

    redis:
        image: redis
        ports:
            - "6379:6379"

    statsd:
        image: hopsoft/graphite-statsd
        ports:
          - "8010:80"
          - "2003:2003"
          - "8125:8125/udp"
          - "8126:8126"
