---
resource_types    :
  - name          : pull-request
    type          : docker-image
    source        :
      repository  : jtarchie/pr

  - name          : slack-notification
    type          : docker-image
    source        :
      repository  : quay.io/hellofresh/slack-notification-resource

  - name          : hf-github-releases
    type          : docker-image
    source        :
      repository  : quay.io/hellofresh/gh-status-dynamic

###############################
# Resources
###############################
resources:
- name: app-master
  type: git
  source:
    uri: {{uri}}
    access_token: {{oauth_token}}
    branch: master

- name          : app-pr
  type          : pull-request
  source        :
    uri         : {{uri}}
    access_token: {{oauth_token}}
    repo        : hellofresh/janus

- name          : gh-release-rc
  type          : hf-github-releases
  source        :
    user        : "hellofresh"
    repository  : "janus"
    access_token: {{oauth_token}}
    pre_release : true

- name          : gh-release-final
  type          : hf-github-releases
  source        :
    user        : "hellofresh"
    repository  : "janus"
    access_token: {{oauth_token}}

- name              : semantic-rc-version
  type              : semver
  source            :
    driver          : git
    initial_version : 0.0.0-rc.1
    uri             : {{uri}}
    branch          : version
    file            : version

- name              : semantic-final-version
  type              : semver
  source            :
    driver          : git
    initial_version : 0.0.0-rc.1
    uri             : {{uri}}
    branch          : version
    file            : version

- name              : automation-release
  type              : github-release
  source            :
    user            : hellofresh
    repository      : automation
    access_token    : {{oauth_token}}

- name              : slack-alert
  type              : slack-notification
  source            :
    url             : {{slack_url}}

###############################
# Groups
###############################
groups:
- name: All
  jobs:
    - master-test-suite
    - build-and-release
    - pullrequest
    - deploy-to-staging
    - promote-release
    - deploy-to-live

- name: Pullrequest
  jobs:
    - pullrequest

- name: Master
  jobs:
    - master-test-suite
    - build-and-release
    - deploy-to-staging

- name: Live
  jobs:
    - promote-release
    - deploy-to-live

###############################
# Jobs
###############################
jobs:

#
# Merge to master
#
- name: master-test-suite
  plan:
  - get: app-master
    trigger: true
  - task: master unit test
    file: app-master/ci/tasks/master-unit-test.yml
    params:
      PROJECT_SRC: {{project_src}}

- name: build-and-release
  public: false
  serial: true
  plan:
  - get: app-master
    trigger: true
    passed: ["master-test-suite"]

  - task: build go app
    file: app-master/ci/tasks/build-staging.yml
    params:
      PROJECT_SRC: {{project_src}}

  - put: semantic-rc-version
    params:
        pre: 'rc'

  - put: gh-release-rc
    params:
      name: semantic-rc-version/version
      tag : semantic-rc-version/version
      globs:
      - artifacts/*.tar.gz

- name: deploy-to-staging
  public: false
  serial: true
  plan:
  - get: gh-release-rc
    trigger: true
    passed: ["build-and-release"]
  - get: app-master
    trigger: false
  - get: automation-release
    trigger: false
  - task: deploy to staging
    file: app-master/ci/tasks/deploy-staging.yml
    on_failure:
        put: slack-alert
        params:
          channel: '#deployments'
          text: |
              The build for app-master failed. Check it out at:
              http://ci000.tools.hellofresh.io:8080/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
              or at:
              http://ci000.tools.hellofresh.io:8080/builds/$BUILD_ID
    on_success:
        put: slack-alert
        params:
          channel: '#deployments'
          text: |
              The build for the app-master was successful. Check it out at:
              http://ci000.tools.hellofresh.io:8080/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
              or at:
              http://ci000.tools.hellofresh.io:8080/builds/$BUILD_ID
    params:
      INPUT: automation-release
      ANSIBLE_REMOTE_USER: jenkins
      VPASS: {{vpass}}
      PRIVATE_KEY: {{private_key}}
      ANSIBLE_PRIVATE_KEY_FILE: /root/.ssh/ansible_id_rsa
      TAR_FILE: automation-release/automation-artifcat.tar.gz
      CI_INVENTORY: "staging.ini"
      GROUP_NAME: "ops-gateway"
      VERSION_FILE: 'gh-release-rc/version'

#
# PR
#
- name: pullrequest
  plan: 
  - get: app-pr
    trigger: true

  - put: app-pr
    params:
        path: app-pr
        context: unit-tests
        status: pending

  - aggregate:
    - task: pullrequest unit test
      file: app-pr/ci/tasks/prequest-unit-tests.yml
      params:
        PROJECT_SRC: {{project_src}}
      on_failure:
          put: app-pr
          params:
              path: app-pr
              context: unit-tests
              status: failure
      on_success:
          put: app-pr
          params:
              path: app-pr
              context: unit-tests
              status: success

#
# Final release
#
- name: promote-release
  serial: true
  plan:
  - get: gh-release-rc

  - put: semantic-final-version
    params:
      bump: final

  - put: gh-release-final
    params:
      # commitish: prerelease/commitish
      globs:
      - gh-release-rc/*.tar.gz
      name: semantic-final-version/version
      tag: semantic-final-version/version

  - put: semantic-final-version
    params:
      bump: patch
      pre: rc

- name: deploy-to-live
  public: false
  serial: true
  plan:
  - get: gh-release-final
    trigger: true
    passed: ["promote-release"]
  - get: app-master
    trigger: false
  - get: automation-release
    trigger: false
  - task: deploy to live
    file: app-master/ci/tasks/deploy-live.yml
    on_failure:
        put: slack-alert
        params:
          channel: '#deployments'
          text: |
              The build for app-master failed. Check it out at:
              http://ci000.tools.hellofresh.io:8080/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
              or at:
              http://ci000.tools.hellofresh.io:8080/builds/$BUILD_ID
    on_success:
        put: slack-alert
        params:
          channel: '#deployments'
          text: |
              The build for the app-master was successful. Check it out at:
              http://ci000.tools.hellofresh.io:8080/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
              or at:
              http://ci000.tools.hellofresh.io:8080/builds/$BUILD_ID
    params:
      INPUT: automation-release
      ANSIBLE_REMOTE_USER: jenkins
      VPASS: {{vpass}}
      PRIVATE_KEY: {{private_key}}
      ANSIBLE_PRIVATE_KEY_FILE: /root/.ssh/ansible_id_rsa
      TAR_FILE: automation-release/automation-artifcat.tar.gz
      CI_INVENTORY: "live.ini"
      GROUP_NAME: "ops-gateway"
      VERSION_FILE: 'gh-release-final/version'